---
title: "Journal (reproducible report)"
author: "Ahmed Elkhateeb"
date: "2020-11-27"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: true
    toc_depth: 3
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```

# Sales Analysis

Last compiled: `r Sys.Date()`

```{r}
# Data Science at TUHH ------------------------------------------------------

# Chapter 2 ----
# SALES ANALYSIS ----

# 2.1 Load libraries ----
  library(tidyverse)
  library(lubridate)
  library(readxl)

# 2.2 Importing Files ----
  bikes_tbl      <- read_excel("data-science/00_data/01_bike_sales/01_raw_data/bikes.xlsx")
  orderlines_tbl <- read_excel("data-science/00_data/01_bike_sales/01_raw_data/orderlines.xlsx")
  bikeshops_tbl  <- read_excel("data-science/00_data/01_bike_sales/01_raw_data/bikeshops.xlsx")

# 2.3 Joining Data ----
  bike_orderlines_joined_tbl <- orderlines_tbl %>%
  left_join(bikes_tbl, by = c("product.id" = "bike.id")) %>%
  left_join(bikeshops_tbl, by = c("customer.id" = "bikeshop.id"))

# 2.4 Wrangling Data ----
  bike_orderlines_wrangled_tbl <- bike_orderlines_joined_tbl %>%
    # 2.4.1 Split location into state and city
    separate(col    = location,
            into   = c("city", "state"),
            sep    = ", ") %>%

    # 2.4.2 Add the total price (price * quantity) 
    mutate(total.price = price * quantity) %>%
  
    # 2.4.3 Rename columns in underscores instead of dots
    set_names(names(.) %>% str_replace_all("\\.", "_"))

# 2.5 Business Insights ----
  
  # 2.5.1 Sales by State
  # Step 1 - Manipulate
  sales_by_location_tbl <- bike_orderlines_wrangled_tbl %>%
  
    # Select columns
    select(state, total_price) %>%
  
    # Grouping by state and summarizing sales
    group_by(state) %>% 
    summarize(sales = sum(total_price)) %>%
  
    # Turn the numbers into a currency format 
    # mutate(sales_text = scales::dollar(sales)) <- Works for dollar values
    mutate(sales_text = scales::dollar(sales, big.mark = ".", 
                                     decimal.mark = ",", 
                                     prefix = "", 
                                     suffix = " €"))

  # Step 2 - Visualize
  sales_by_location_tbl %>%
  
    # Setup canvas with the columns year (x-axis) and sales (y-axis)
    ggplot(aes(x = state, y = sales)) +
  
    # Geometries
    geom_col(fill = "#2DC6D6") + # Use geom_col for a bar plot
    geom_label(aes(label = sales_text)) + # Adding labels to the bars
    geom_smooth(method = "lm", se = FALSE) + # Adding a trendline
  
    # Formatting
    # scale_y_continuous(labels = scales::dollar) + # Change the y-axis. 
    # Again, we have to adjust it for euro values
    scale_y_continuous(labels = scales::dollar_format(big.mark = ".", 
                                                    decimal.mark = ",", 
                                                    prefix = "", 
                                                    suffix = " €")) +
    labs(
      title    = "Revenue by state",
      subtitle = "",
      x = "", # Override defaults for x and y
      y = "Revenue"
    ) +
  
    #rotate x-axis labels
    theme(axis.text.x = element_text(angle = 45, hjust = 1))

  # 2.5.2 Sales by Year and Location

  # Step 1 - Manipulate
  sales_by_year_location_tbl <- bike_orderlines_wrangled_tbl %>%
  
    # Select columns and add a year
    select(order_date, total_price, state) %>%
    mutate(year = year(order_date)) %>%
  
    # Group by and summarize year and main catgegory
    group_by(year, state) %>%
    summarise(sales = sum(total_price)) %>%
    ungroup() %>%
  
    # Format $ Text
    mutate(sales_text = scales::dollar(sales, big.mark = ".", 
                                      decimal.mark = ",", 
                                      prefix = "", 
                                      suffix = " €"))

  # Step 2 - Visualize
  sales_by_year_location_tbl %>%
  
    # Set up x, y, fill
    ggplot(aes(x = year, y = sales, fill = state)) +
  
    # Geometries
    geom_col() + # Run up to here to get a stacked bar plot
  
    # Facet
    facet_wrap(~ state) +
  
    # Formatting
    scale_y_continuous(labels = scales::dollar_format(big.mark = ".", 
                                                    decimal.mark = ",", 
                                                    prefix = "", 
                                                    suffix = " €")) +
    labs(
      title = "Revenue by year and location",
      subtitle = "",
      fill = "States" # Changes the legend name
    ) +

    #rotate x-axis labels
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

# API Data Retrieval

Last compiled: `r Sys.Date()`

```{r}
# Data Science at TUHH ------------------------------------------------------

# Chapter 3 ----

# 3.1 API data retrieval ----

# 3.1.0 Load libraries

library(httr)
library(glue)
library(jsonlite)
library(keyring)

# 3.1.1 Code
#Returns information for the top 50 cities worldwide.

#keyring::key_set("token")

api_key = key_get("token")

url <- modify_url(url = "http://dataservice.accuweather.com", path = glue("/locations/v1/topcities/50?apikey={api_key}&language=en-us&details=false"))

raw_data <- GET(url)

stop_for_status(raw_data) # automatically throws an error if a request did not succeed

data_list <- raw_data %>% 
  .$content %>% 
  rawToChar() %>% 
  fromJSON()

glimpse(data_list)
```

# Web Scraping

```{r}
# Data Science at TUHH ------------------------------------------------------

# Chapter 3 ----

# 3.2 WEBSCRAPING ----

# 3.2.0 Load libraries

library(tidyverse) # Main Package - Loads dplyr, purrr, etc.
library(rvest)     # HTML Hacking & Web Scraping
library(xopen)     # Quickly opening URLs
library(jsonlite)  # converts JSON files to R objects
library(glue)      # concatenate strings
library(stringi)   # character string/text processing

# 3.2.1 COLLECT PRODUCT FAMILIES

url_home          <- "https://www.rosebikes.de/"

# Read in the HTML for the entire home webpage
html_home         <- read_html(url_home)

# Web scrape the urls for the families
bike_family_tbl <- html_home %>%
  
  # Get the nodes for the families ...
  html_nodes(css = ".main-navigation-category-with-tiles__link ") %>%
  
  # ...and extract the href information
  html_attr('href') %>%
  
  # Remove the product families sale 
  discard(.p = ~stringr::str_detect(.x,"sale$")) %>%
  
  # Convert vector to tibble
  enframe(name = "position", value = "family_class") %>%
  
  # Save the family urls
  transmute(family_url = str_glue("https://www.rosebikes.de{family_class}"))

# 3.2.2 COLLECT Gravel Categories 

# Read in the HTML for the entire Gravel family webpage
html_family         <- read_html(bike_family_tbl$family_url[3])

bike_category_tbl <- html_family %>%
  
  #Get the nodes for categories
  html_nodes(css = ".catalog-category-bikes__picture-wrapper") %>%
  
  # ...and extract the href information
  html_attr('href') %>%
  
  # Convert vector to tibble
  enframe(name = "position", value = "subdirectory") %>%
  
  # Save the Categories urls
  transmute(position, category_url = str_glue("https://www.rosebikes.de{subdirectory}"))

# 3.2.3 COLLECT Gravel/Backroad Bike Models 

# Read in the HTML for the entire Gravel/Backroad category webpage
html_models         <- read_html(bike_category_tbl$category_url[2])

bike_model_1_tbl <- html_models %>%
  
  #Get the nodes for bike models
  html_nodes(css = ".catalog-category-model__title") %>%
  
  #...and extract the text
  html_text()%>%
  
  # Convert vector to tibble
  enframe(name = "position", value = "model")


#Read models prices
model_price_1_tbl <- html_models %>%
  
  #Get the nodes for bike models prices
  html_nodes(css = ".catalog-category-model__price-current-value") %>%
  
  #...and extract the text
  html_text()%>%
  
  # Convert vector to tibble
  enframe(name = "position", value = "price")

#Joining category, model and price
bike_model_1_tbl <- left_join(bike_model_1_tbl, model_price_1_tbl, by = c("position")) %>%
  tibble(category= bike_category_tbl$category_url[2]) %>% 
  separate(col    = category,
           into   = c("remove", "category"),
           sep    = "fahrräder/") %>% 
  select(position, category, model, price)

# 3.2.4 COLLECT Gravel/Backroad al Bike Models 

# Read in the HTML for the entire Gravel/Backroad category webpage
html_models         <- read_html(bike_category_tbl$category_url[1])

bike_model_2_tbl <- html_models %>%
  
  #Get the nodes for bike models
  html_nodes(css = ".catalog-category-model__title") %>%
  
  #...and extract the text
  html_text()%>%
  
  # Convert vector to tibble
  enframe(name = "position", value = "model")

#Read models prices
model_price_2_tbl <- html_models %>%
  
  #Get the nodes for bike models prices
  html_nodes(css = ".catalog-category-model__price-current-value") %>%
  
  #...and extract the text
  html_text()%>%
  
  # Convert vector to tibble
  enframe(name = "position", value = "price")

#Joining category, model and price
bike_model_2_tbl <- left_join(bike_model_2_tbl, model_price_2_tbl, by = c("position")) %>%
  tibble(category= bike_category_tbl$category_url[1]) %>% 
  separate(col    = category,
           into   = c("remove", "category"),
           sep    = "fahrräder/") %>% 
  select(position, category, model, price)

# 3.2.5 COLLECT Gravel/Backroad limited Bike Models 

# Read in the HTML for the entire Gravel/Backroad category webpage
html_models         <- read_html(bike_category_tbl$category_url[3])

bike_model_3_tbl <- html_models %>%
  
  #Get the nodes for bike models
  html_nodes(css = ".catalog-category-model__title") %>%
  
  #...and extract the text
  html_text()%>%
  
  # Convert vector to tibble
  enframe(name = "position", value = "model")


#Read models prices
model_price_3_tbl <- html_models %>%
  
  #Get the nodes for bike models prices
  html_nodes(css = ".catalog-category-model__price-current-value") %>%
  
  #...and extract the text
  html_text()%>%
  
  # Convert vector to tibble
  enframe(name = "position", value = "price")

#Joining category, model and price
bike_model_3_tbl <- left_join(bike_model_3_tbl, model_price_3_tbl, by = c("position")) %>%
  tibble(category= bike_category_tbl$category_url[3]) %>% 
  separate(col    = category,
           into   = c("remove", "category"),
           sep    = "fahrräder/") %>% 
  select(position, category, model, price)

#Bind 3 categories tables
bike_model_tbl <- bike_model_3_tbl %>%
  rbind(bike_model_2_tbl) %>%
  rbind(bike_model_1_tbl)

#Print first 10 rows
bike_model_tbl %>% head(n = 10)
```
